language: php

php:
  - 5.6
  - '7.0'
  - hhvm
  - nightly

sudo: false

before_script:
 - phpenv rehash > /dev/null
 - composer selfupdate --quiet
 - composer install --no-interaction --prefer-source --dev
